export enum INPUT_VALUES_ENUM {
  EMAIL = "EMAIL",
  PASSWORD = "PASSWORD",
  REPEAT_PASSWORD = "REPEAT_PASSWORD",
  PRIVACY_POLICY = "PRIVACY_POLICY",
}

export enum AUTH_MODE_ENUM {
  LOGIN = "LOGIN",
  REGISTER = "REGISTER",
}
